#!/usr/bin/ruby
# короче, штанготрекер
#должен уметь: заводить новый training day с таймстампом
#в trday записывать упражнения и их веса

#писать это в базу и читать из нее

# виды упражнений со штангой берем из книги Starting Strength

# после какого-то момента — создавать новые упражнения

# когда-нибудь — строить графики итд

#first, we do a logbook for one person:

logbook = {}

# add value routine
def add (ex_db, ex_name, weight, reps)
  ex_db[ex_name] = (weight, reps)
  puts "#{ex_name} => #{weight}"